version: '3.2'

# docker config
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - yii2
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HTTP_PORT:-80}:80
  yii2:
    image: yiisoftware/yii2-php:8.0-fpm
    working_dir: /app/app
    depends_on:
      - postgresql
      - redis
    volumes:
      - .:/app
    environment:
      PHP_USER_ID: ${PHP_USER_ID:-33}
  postgresql:
    build: ./docker/postgresql
    volumes:
      - "./storage/db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    ports:
      - ${DB_PORT:-5432}:5432

  redis:
    image: redis:7.2.1-alpine

